# Generated by Django 4.0.1 on 2022-03-01 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookpost',
            options={'ordering': ['-created_on'], 'verbose_name': 'Livre'},
        ),
        migrations.AlterField(
            model_name='bookpost',
            name='created_on',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
