# Generated by Django 4.0.1 on 2022-03-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_bookpost_options_alter_bookpost_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpost',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
