# Generated by Django 4.0.1 on 2022-03-05 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_bookpost_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpost',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bookpost',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='book', verbose_name='Image'),
        ),
    ]
