# Generated by Django 4.0.1 on 2022-03-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_bookpost_score_alter_bookpost_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpost',
            name='score',
        ),
    ]
